version: "3"
services:
 api:
  restart: always
  container_name: api
  build:
   context: ./api
   dockerfile: Dockerfile
  # command: "flask run --host=0.0.0.0"
  networks:
   - frontend-zpeek-network
  environment:
   - FLASK_ENV=production
   - FLASK_APP=test.py
   - FLASK_DEBUG=1
  ports:
   - 5000:5000
 frontend:
  container_name: frontend
  build:
   context: ./frontend
   dockerfile: Dockerfile
  depends_on:
    - api
  networks:
   - frontend-zpeek-network
   - backend-zpeek-network
  ports:
   - 80:80
networks:
 frontend-zpeek-network:
  driver: bridge
 backend-zpeek-network:
  driver: bridge
